spring.application.name=Integrador
groq.api.key={apikey}
groq.api.url={apikey}




spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


spring.datasource.url=jdbc:mysql://localhost:3306/ANIMALFEED
spring.datasource.username=root
spring.datasource.password=luis

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# 1. LOGS: Generar archivo físico automático en la raíz del proyecto
logging.file.name=logs/animalfeed_monitoring.log
logging.level.com.example.Integrador=INFO
# 2. SALUD Y RENDIMIENTO: Exponer los paneles de monitoreo nativos
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always





spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=david08af@gmail.com
spring.mail.password=dhhlqpggdxvnkndq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
